const samples = [
    { "email": "alice@example.com", "title": "Welcome!", "message": "Hello Alice, welcome aboard." },
    { "email": "bob@example.com", "title": "Update", "message": "Hi Bob, here's your update." },
    { "email": "carol@example.com", "title": "Reminder", "message": "Carol, don't forget our meeting." },
    { "email": "dave@example.com", "title": "Greetings", "message": "Dave, greetings from the team." },
    { "email": "eve@example.com", "title": "Alert", "message": "Eve, please check your inbox." },
    { "email": "frank@example.com", "title": "Invitation", "message": "Frank, you're invited!" },
    { "email": "grace@example.com", "title": "Notice", "message": "Grace, please read this notice." },
    { "email": "billy@example.com", "title": "Survey", "message": "Billy, please take our survey." },
    { "email": "ivan@example.com", "title": "Welcome!", "message": "Ivan, welcome to the platform." },
    { "email": "judy@example.com", "title": "Update", "message": "Judy, here's your update." },
    { "email": "karl@example.com", "title": "Info", "message": "Karl, here is your info." },
    { "email": "lisa@example.com", "title": "Greetings", "message": "Lisa, greetings from us." },
    { "email": "mike@example.com", "title": "Alert", "message": "Mike, please check your inbox." },
    { "email": "nina@example.com", "title": "Follow Up", "message": "Nina, following up on your request." },
    { "email": "oliver@example.com", "title": "News", "message": "Oliver, here's the latest news." },
    { "email": "paul@example.com", "title": "Invitation", "message": "Paul, you're invited!" },
    { "email": "quinn@example.com", "title": "Notice", "message": "Quinn, please read this notice." },
    { "email": "rachel@example.com", "title": "Survey", "message": "Rachel, please take our survey." },
    { "email": "sam@example.com", "title": "Welcome!", "message": "Sam, welcome to the platform." },
    { "email": "tina@example.com", "title": "Update", "message": "Tina, here's your update." },
    { "email": "ursula@example.com", "title": "Reminder", "message": "Ursula, don't forget our meeting." },
    { "email": "victor@example.com", "title": "Alert", "message": "Victor, please check your inbox." },
    { "email": "wendy@example.com", "title": "Follow Up", "message": "Wendy, following up on your request." },
    { "email": "xander@example.com", "title": "News", "message": "Xander, here's the latest news." },
    { "email": "yvonne@example.com", "title": "Invitation", "message": "Yvonne, you're invited!" },
    { "email": "zach@example.com", "title": "Notice", "message": "Zach, please read this notice." },
    { "email": "amy@example.com", "title": "Survey", "message": "Amy, please take our survey." },
    { "email": "ben@example.com", "title": "Welcome!", "message": "Ben, welcome to the platform." },
    { "email": "claire@example.com", "title": "Update", "message": "Claire, here's your update." },
    { "email": "dan@example.com", "title": "Reminder", "message": "Dan, don't forget our meeting." },
    { "email": "ella@example.com", "title": "Alert", "message": "Ella, please check your inbox." },
    { "email": "finn@example.com", "title": "Follow Up", "message": "Finn, following up on your request." },
    { "email": "gina@example.com", "title": "News", "message": "Gina, here's the latest news." },
    { "email": "harry@example.com", "title": "Invitation", "message": "Harry, you're invited!" },
    { "email": "iris@example.com", "title": "Notice", "message": "Iris, please read this notice." },
    { "email": "jack@example.com", "title": "Survey", "message": "Jack, please take our survey." },
    { "email": "kate@example.com", "title": "Welcome!", "message": "Kate, welcome to the platform." },
    { "email": "leo@example.com", "title": "Update", "message": "Leo, here's your update." },
    { "email": "maya@example.com", "title": "Reminder", "message": "Maya, don't forget our meeting." },
    { "email": "noah@example.com", "title": "Alert", "message": "Noah, please check your inbox." },
    { "email": "heidi@example.com", "title": "Project Update", "message": "Heidi, your project status has changed." },
    { "email": "heidi@example.com", "title": "Team Meeting", "message": "Heidi, please join the team meeting tomorrow." },
    { "email": "heidi@example.com", "title": "Document Review", "message": "Heidi, review the attached document." },
    { "email": "heidi@example.com", "title": "Feedback Request", "message": "Heidi, we need your feedback." },
    { "email": "heidi@example.com", "title": "System Alert", "message": "Heidi, there is a new system alert." },
    { "email": "heidi@example.com", "title": "Training Session", "message": "Heidi, training session scheduled for Friday." },
    { "email": "heidi@example.com", "title": "Resource Update", "message": "Heidi, new resources are available." },
    { "email": "heidi@example.com", "title": "Policy Change", "message": "Heidi, company policy has been updated." },
    { "email": "heidi@example.com", "title": "Performance Review", "message": "Heidi, your performance review is ready." },
    { "email": "heidi@example.com", "title": "Security Notice", "message": "Heidi, please read the latest security notice." }
];

export default samples;